# Ex - GroupBy (part a)

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries

In [33]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

### Step 3. Assign it to a variable called drinks.

In [34]:
drinks = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv", sep = ',')

### Step 4. Which continent drinks more beer on average?

In [35]:
# # Algorithmic solution without groupby

# beer_dict = {"AF": 0, "AS": 0, "EU": 0, "OC": 0, "SA": 0}
# for continent in list(beer_dict.keys()):
#     curr_beer_count = drinks.loc[drinks["continent"] == continent, "beer_servings"].sum()
#     curr_continent_count = drinks.loc[drinks["continent"] == continent, "continent"].shape[0]
#     beer_dict[continent] = curr_beer_count/curr_continent_count

# beer_avg_list = list(beer_dict.values())
# max_beer_index = beer_avg_list.index(max(beer_avg_list))
# max_continent = list(beer_dict.keys())[max_beer_index]

# print(max_continent)

# # With groupby, not optimal

# beer_servings_summary = drinks.groupby(["continent"])["beer_servings"].mean()
# continent_list = list(dict(beer_servings_summary).keys())
# beer_servings_summary.sort_values().tail(1)

beer_servings_summary = drinks.groupby(["continent"])["beer_servings"].mean()
beer_servings_summary.idxmax()

'EU'

### Step 5. For each continent print the statistics for wine consumption.

In [36]:
drinks.groupby(["continent"])["wine_servings"].mean()

continent
AF     16.264151
AS      9.068182
EU    142.222222
OC     35.625000
SA     62.416667
Name: wine_servings, dtype: float64

### Step 6. Print the mean alcohol consumption per continent for every column

In [37]:
drinks.groupby(["continent"])[drinks.columns[1:-1]].mean()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,61.471698,16.339623,16.264151,3.007547
AS,37.045455,60.840909,9.068182,2.170455
EU,193.777778,132.555556,142.222222,8.617778
OC,89.687500,58.437500,35.625000,3.381250
SA,175.083333,114.750000,62.416667,6.308333

### Step 7. Print the median alcohol consumption per continent for every column

In [38]:
drinks.groupby(["continent"])[drinks.columns[1:-1]].median()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,32.0,3.0,2.0,2.30
AS,17.5,16.0,1.0,1.20
EU,219.0,122.0,128.0,10.00
OC,52.5,37.0,8.5,1.75
SA,162.5,108.5,12.0,6.85

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [42]:
mean_spirit = drinks.groupby(["continent"])["spirit_servings"].mean()
min_spirit = drinks.groupby(["continent"])["spirit_servings"].min()
max_spirit = drinks.groupby(["continent"])["spirit_servings"].max()

spirit_statistics_dict = {"continent": mean_spirit.index, "mean": mean_spirit, "min": min_spirit, "max": max_spirit}
spirit_statistics = pd.DataFrame(spirit_statistics_dict)
spirit_statistics.set_index("continent")

                 mean  min  max
continent
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302