# Occupation (part b)

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [3]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep = "|")

### Step 4. Discover what is the mean age per occupation

In [4]:
users.groupby(["occupation"])[["age"]].mean()

                     age
occupation
administrator  38.746835
artist         31.392857
doctor         43.571429
educator       42.010526
engineer       36.388060
entertainment  29.222222
executive      38.718750
healthcare     41.562500
homemaker      32.571429
lawyer         36.750000
librarian      40.000000
marketing      37.615385
none           26.555556
other          34.523810
programmer     33.121212
retired        63.071429
salesman       35.666667
scientist      35.548387
student        22.081633
technician     33.148148
writer         36.311111

### Step 6. For each occupation, calculate the minimum and maximum ages

In [8]:
# occupation_list = list(set(list(users.iloc[:]["occupation"])))

occupation_list = users["occupation"].unique()
min_age = users.groupby(["occupation"])["age"].min()
max_age = users.groupby(["occupation"])["age"].max()

final_dict = {"occupation": occupation_list, "min_age": min_age, "max_age": max_age}
final_df = pd.DataFrame(final_dict)
final_df

                  occupation  min_age  max_age
occupation
administrator     technician       21       70
artist                 other       19       48
doctor                writer       28       64
educator           executive       23       63
engineer       administrator       22       70
entertainment        student       15       50
executive             lawyer       22       69
healthcare          educator       22       62
homemaker          scientist       20       50
lawyer         entertainment       21       53
librarian         programmer       23       69
marketing          librarian       24       55
none               homemaker       11       55
other                 artist       13       64
programmer          engineer       20       63
retired            marketing       51       73
salesman                none       18       66
scientist         healthcare       23       55
student              retired        7       42
technician          salesman       21       55
writer                doctor       18       60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [4]:
users.groupby(["occupation", "gender"])[["age"]].mean()

                            age
occupation    gender
administrator F       40.638889
              M       37.162791
artist        F       30.307692
              M       32.333333
doctor        M       43.571429
educator      F       39.115385
              M       43.101449
engineer      F       29.500000
              M       36.600000
entertainment F       31.000000
              M       29.000000
executive     F       44.000000
              M       38.172414
healthcare    F       39.818182
              M       45.400000
homemaker     F       34.166667
              M       23.000000
lawyer        F       39.500000
              M       36.200000
librarian     F       40.000000
              M       40.000000
marketing     F       37.200000
              M       37.875000
none          F       36.500000
              M       18.600000
other         F       35.472222
              M       34.028986
programmer    F       32.166667
              M       33.216667
retired       F       70.000000
              M       62.538462
salesman      F       27.000000
              M       38.555556
scientist     F       28.333333
              M       36.321429
student       F       20.750000
              M       22.669118
technician    F       38.000000
              M       32.961538
writer        F       37.631579
              M       35.346154

### Step 8.  For each occupation present the percentage of women and men

In [51]:
sum_gender = users.groupby(["occupation"])[["gender"]].sum()
men_percentage_column, women_percentage_column = [], []

for i in range(len(occupation_list)):
    gender_list = list(sum_gender.iloc[i, 0])
    men_percentage_column.append(len([i for i in range(len(gender_list)) if gender_list[i] == 'M'])/len(gender_list) * 100)
    women_percentage_column.append(100 - men_percentage)

del sum_gender["gender"]
sum_gender["men (%)"] = men_percentage_column
sum_gender["women (%)"] = women_percentage_column
sum_gender

                  men (%)  women (%)
occupation
administrator   54.430380  99.422222
artist          53.571429  99.422222
doctor         100.000000  99.422222
educator        72.631579  99.422222
engineer        97.014925  99.422222
entertainment   88.888889  99.422222
executive       90.625000  99.422222
healthcare      31.250000  99.422222
homemaker       14.285714  99.422222
lawyer          83.333333  99.422222
librarian       43.137255  99.422222
marketing       61.538462  99.422222
none            55.555556  99.422222
other           65.714286  99.422222
programmer      90.909091  99.422222
retired         92.857143  99.422222
salesman        75.000000  99.422222
scientist       90.322581  99.422222
student         69.387755  99.422222
technician      96.296296  99.422222
writer          57.777778  99.422222