# Regiment (part c)

### Introduction:

Special thanks to: http://chrisalbon.com/ for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [5]:
import pandas as pd

### Step 2. Create the DataFrame with the following values:

In [6]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'], 
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'], 
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

### Step 3. Assign it to a variable called regiment.
#### Don't forget to name each column

In [7]:
regiment = pd.DataFrame(raw_data, columns=raw_data.keys())

### Step 4. What is the mean preTestScore from the regiment Nighthawks?

In [9]:
all_means_preTestScore = regiment.groupby(["regiment"])[["preTestScore"]].mean()
all_means_preTestScore.loc["Nighthawks"]

preTestScore    15.25
Name: Nighthawks, dtype: float64

### Step 5. Present general statistics by company

In [10]:
# regiment.groupby(["company"])[["preTestScore", "postTestScore"]].mean()
# Only mean? How can I present all statistics, by company?

regiment.groupby(["company"])[["name", "preTestScore", "postTestScore"]].agg(
    # name_count = ("name", "count"),
    
    preTestScore_min = ("preTestScore", "min"),
    preTestScore_max = ("preTestScore", "max"),
    preTestScore_mean = ("preTestScore", "mean"),
    preTestScore_median = ("preTestScore", "min"),

    postTestScore_min = ("postTestScore", "min"),
    postTestScore_max = ("postTestScore", "max"),
    postTestScore_mean = ("postTestScore", "mean"),
    postTestScore_median = ("postTestScore", "min")   
    )

,preTestScore_min,preTestScore_max,preTestScore_mean,preTestScore_median,postTestScore_min,postTestScore_max,postTestScore_mean,postTestScore_median
company,,,,,,,,
1st,2,24,6.666667,2,25,94,57.666667,25
2nd,2,31,15.500000,2,57,94,67.000000,57

### Step 6. What is the mean of each company's preTestScore?

In [11]:
regiment.groupby(["company"])[["preTestScore"]].mean()

         preTestScore
company
1st          6.666667
2nd         15.500000

### Step 7. Present the mean preTestScores grouped by regiment and company

In [12]:
regiment.groupby(["regiment", "company"])[["preTestScore"]].mean()

                    preTestScore
regiment   company
Dragoons   1st               3.5
           2nd              27.5
Nighthawks 1st              14.0
           2nd              16.5
Scouts     1st               2.5
           2nd               2.5

### Step 8. Present the mean preTestScores grouped by regiment and company without heirarchical indexing

In [13]:
regiment.groupby(["regiment", "company"], sort=False)[["preTestScore"]].mean()

                    preTestScore
regiment   company
Nighthawks 1st              14.0
           2nd              16.5
Dragoons   1st               3.5
           2nd              27.5
Scouts     1st               2.5
           2nd               2.5

### Step 9. Group the entire dataframe by regiment and company

In [14]:
final_grouping = regiment.groupby(["regiment", "company"])

### Step 10. What is the number of observations in each regiment and company

In [15]:
final_grouping[["name"]].agg(count = ("name", "count"))

                    count
regiment   company
Dragoons   1st          2
           2nd          2
Nighthawks 1st          2
           2nd          2
Scouts     1st          2
           2nd          2

### Step 11. Iterate over a group and print the name and the whole data from the regiment

In [17]:
regiment_list = regiment["regiment"].unique()
for curr_regiment in regiment_list:
    print(curr_regiment)
    print(regiment.loc[regiment["regiment"] == curr_regiment])

Nighthawks
     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
Dragoons
   regiment company    name  preTestScore  postTestScore
4  Dragoons     1st   Cooze             3             70
5  Dragoons     1st   Jacon             4             25
6  Dragoons     2nd  Ryaner            24             94
7  Dragoons     2nd    Sone            31             57
Scouts
   regiment company   name  preTestScore  postTestScore
8    Scouts     1st  Sloan             2             62
9    Scouts     1st  Piger             3             70
10   Scouts     2nd  Riani             2             62
11   Scouts     2nd    Ali             3             70