# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [1]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data", sep=r"\s+")
# sep = r"\s+" works for this case of space seperator (sep = " " doesn't work)

add_20 = lambda x : "20" + str(x)
data['Yr'] = data['Yr'].apply(add_20)
# data['Yr'] = ["20" + str(x) for x in data['Yr']]

data['date'] = pd.to_datetime(dict(year=data.Yr, month=data.Mo, day=data.Dy))

del data['Yr']
del data['Mo']
del data['Dy']

data = data.set_index('date')

data

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...
2078-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
2078-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
2078-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
2078-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
2078-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [7]:
def decrease_year(dates_list, param):
    # Without for loop
    return dates_list - pd.DateOffset(years=param)
    
    # # With for loop (invalid)
    # return [pd.to_datetime(str(curr_date.year - param) + " " + str(curr_date.month) + " " + str(curr_date.day)) for curr_date in dates_list]

new_dates_list = decrease_year(data.index, 100)

# Is valid
# print(new_dates_list[-1].year < 2026)

data

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [8]:
data = data.reset_index(drop=True)
data["date"] = new_dates_list
data = data.set_index("date")

data
# data = data.reindex(new_dates_list) didnt work

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
1861-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1861-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1861-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1861-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1861-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...
1878-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
1878-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
1878-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
1878-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
1878-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [9]:
missing_count = data.isna().sum().sum()
missing_count

np.int64(31)

### Step 7. Compute how many non-missing values there are in total.

In [11]:
non_missing_count = data.shape[0] * data.shape[1] - missing_count
non_missing_count

np.int64(78857)

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [12]:
data.sum().sum()/non_missing_count

np.float64(10.227883764282181)

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [13]:
# # One approach without for loops
# loc_stats = data.describe()
# loc_stats.loc[["min", "max", "mean", "std"]][:]

# Second approach without for loops
loc_stats = (
    data.apply(lambda x: pd.Series({
            "min": np.nanmin(x.values),
            "max": np.nanmax(x.values),
            "mean": np.nanmean(x.values),
            "std": np.nanstd(x.values)
        }))
)

loc_stats

# # With for loops (invalid)

# # Initialize the new data frame
# loc_stats = pd.DataFrame([], columns=data.columns, index=["min", "max", "mean", "std"])

# # min, max, mean, std
# for curr_location in list(data.columns):
#     loc_stats.loc["min", curr_location] = data[curr_location].min() 
#     loc_stats.loc["max", curr_location] = data[curr_location].max() 
#     loc_stats.loc["mean", curr_location] = data[curr_location].mean() 
#     loc_stats.loc["std", curr_location] = data[curr_location].std()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.617985,5.266956,5.008069,3.605537,4.935750,3.968381,4.977176,4.499107,4.166555,4.503612,5.834593,6.699284

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [15]:
# The correct approach:
# .groupby stack the data into groups
# .apply, applies the function on each group (row)

modified_data = data
modified_data.index.name = None

day_stats = (
    data.groupby(modified_data.index.day)
        .apply(lambda x: pd.Series({
            "min": np.nanmin(x.values),
            "max": np.nanmax(x.values),
            "mean": np.nanmean(x.values),
            "std": np.nanstd(x.values)
        }))
        .T
)
day_stats

# # With for loop (invalid)
# def drop_nan(numpy_list):
#     return numpy_list[~np.isnan(numpy_list)]

# day_grouping = data.groupby([data.index.day])  # Group the df by day
# days_list = list(set(list(data.index.day)))  # Days list (the column of the new df)
# day_stats = pd.DataFrame([], columns = days_list, index = ["min", "max", "mean", "std"])  # The new df

# # Loop over all days
# for i in range(len(days_list)):
#     curr_day = days_list[i]
#     data_day = drop_nan(list(day_grouping)[i][1].to_numpy().flatten()) # Flatten the data frame
    
#     day_stats.loc["min", curr_day] = data_day.min()
#     day_stats.loc["max", curr_day] = data_day.max()
#     day_stats.loc["mean", curr_day] = data_day.mean()
#     day_stats.loc["std", curr_day] = data_day.std()

# day_stats

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
min,0.170000,0.000000,0.000000,0.000000,0.130000,0.000000,0.040000,0.040000,0.000000,0.000000,...,0.130000,0.000000,0.080000,0.170000,0.000000,0.000000,0.040000,0.000000,0.080000,0.080000
max,42.380000,42.540000,31.750000,29.540000,33.790000,36.510000,35.800000,38.040000,38.200000,33.870000,...,34.080000,34.830000,32.910000,38.960000,33.420000,40.080000,41.460000,38.200000,34.250000,37.630000
mean,10.530626,10.390000,9.919537,9.808286,10.114915,10.015224,10.101177,9.902049,10.399803,10.529325,...,10.006636,10.505355,10.392154,10.435988,9.928259,10.345127,10.207668,10.337106,10.624884,10.410893
std,5.696817,5.758227,5.301837,5.340918,5.325267,5.681374,5.611563,5.358177,5.517022,5.718327,...,5.532097,5.374535,5.421869,5.520602,5.509253,5.863826,5.524404,5.560221,5.461673,5.555065

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [16]:
January_filter = data.loc[data.index.month == 1]
January_filter.apply(lambda x: pd.Series({"mean": np.nanmin(x.values)})).T

     mean
RPT  0.67
VAL  0.54
ROS  2.75
KIL  0.08
SHA  0.42
BIR  0.04
DUB  0.46
CLA  0.00
MUL  0.29
CLO  0.04
BEL  0.13
MAL  3.25

### Step 12. Downsample the record to a yearly frequency for each location.

In [17]:
# Yearly_frequency = data.groupby(data.index.year)
Yearly_frequency = data.groupby(pd.Grouper(freq="YE"))
Yearly_frequency.count()

            RPT  VAL  ROS  KIL  SHA  BIR  DUB  CLA  MUL  CLO  BEL  MAL
1861-12-31  360  362  363  361  363  365  362  363  362  364  365  362
1862-12-31  364  365  365  364  365  365  365  365  365  365  365  364
1863-12-31  365  365  365  365  365  365  365  365  365  365  365  365
1864-12-31  366  366  366  366  366  366  366  366  366  366  366  366
1865-12-31  365  365  365  365  365  365  365  365  365  365  365  365
1866-12-31  365  365  365  365  365  365  365  365  365  365  365  365
1867-12-31  365  365  365  365  365  365  365  365  365  365  365  365
1868-12-31  366  366  366  366  366  366  366  366  366  366  366  366
1869-12-31  365  365  365  365  365  365  365  365  365  365  365  365
1870-12-31  365  365  365  365  365  365  365  365  365  365  365  365
1871-12-31  365  365  365  365  365  365  365  365  365  365  365  365
1872-12-31  366  366  366  366  366  366  366  366  366  366  366  366
1873-12-31  365  365  365  365  365  365  365  365  365  365  365  365
1874-12-31  365  365  365  365  365  365  365  365  365  365  365  365
1875-12-31  365  365  365  365  365  365  365  365  365  365  365  365
1876-12-31  366  366  366  366  366  366  366  366  366  366  366  366
1877-12-31  365  365  365  365  365  365  365  365  365  365  365  365
1878-12-31  365  365  365  365  365  365  365  365  365  365  365  365

### Step 13. Downsample the record to a monthly frequency for each location.

In [18]:
# Monthly_frequency = data.groupby(data.index.month)
Monthly_frequency = data.groupby(pd.Grouper(freq="ME"))
Monthly_frequency.count()

            RPT  VAL  ROS  KIL  SHA  BIR  DUB  CLA  MUL  CLO  BEL  MAL
1861-01-31   30   30   31   31   29   31   31   30   31   31   31   31
1861-02-28   28   28   27   27   28   28   28   28   28   28   28   28
1861-03-31   30   31   31   30   31   31   31   31   29   31   31   30
1861-04-30   30   30   30   30   30   30   30   30   30   30   30   30
1861-05-31   31   30   31   30   31   31   30   31   31   31   31   31
...         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
1878-08-31   31   31   31   31   31   31   31   31   31   31   31   31
1878-09-30   30   30   30   30   30   30   30   30   30   30   30   30
1878-10-31   31   31   31   31   31   31   31   31   31   31   31   31
1878-11-30   30   30   30   30   30   30   30   30   30   30   30   30
1878-12-31   31   31   31   31   31   31   31   31   31   31   31   31

[216 rows x 12 columns]

### Step 14. Downsample the record to a weekly frequency for each location.

In [19]:
# Weekly_frequency = data.groupby(data.index.day // 7)
Weekly_frequency = data.groupby(pd.Grouper(freq="W"))
Weekly_frequency.count()

            RPT  VAL  ROS  KIL  SHA  BIR  DUB  CLA  MUL  CLO  BEL  MAL
1861-01-06    6    5    6    6    5    6    6    5    6    6    6    6
1861-01-13    7    7    7    7    7    7    7    7    7    7    7    7
1861-01-20    7    7    7    7    6    7    7    7    7    7    7    7
1861-01-27    7    7    7    7    7    7    7    7    7    7    7    7
1861-02-03    6    7    7    7    7    7    7    7    7    7    7    7
...         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
1878-12-08    7    7    7    7    7    7    7    7    7    7    7    7
1878-12-15    7    7    7    7    7    7    7    7    7    7    7    7
1878-12-22    7    7    7    7    7    7    7    7    7    7    7    7
1878-12-29    7    7    7    7    7    7    7    7    7    7    7    7
1879-01-05    2    2    2    2    2    2    2    2    2    2    2    2

[940 rows x 12 columns]

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [20]:
# First week starts on January 1 1961

weekly_stats = (
    Weekly_frequency.apply(lambda x: pd.Series({
            "min": np.nanmin(x.values),
            "max": np.nanmax(x.values),
            "mean": np.nanmean(x.values),
            "std": np.nanstd(x.values)
    })).iloc[:52, :].T
        
)
weekly_stats

,1861-01-06,1861-01-13,1861-01-20,1861-01-27,1861-02-03,1861-02-10,1861-02-17,1861-02-24,1861-03-03,1861-03-10,...,1861-10-27,1861-11-03,1861-11-10,1861-11-17,1861-11-24,1861-12-01,1861-12-08,1861-12-15,1861-12-22,1861-12-29
min,1.790000,0.580000,0.500000,2.170000,3.630000,8.080000,3.420000,2.210000,6.420000,1.710000,...,6.080000,1.710000,1.330000,0.630000,2.880000,1.920000,3.130000,3.830000,0.580000,0.420000
max,18.500000,20.710000,20.790000,27.630000,27.710000,26.380000,28.620000,29.630000,25.800000,18.160000,...,30.880000,23.580000,18.710000,32.710000,22.580000,23.750000,29.330000,25.620000,16.210000,24.410000
mean,10.171449,9.810595,8.474819,14.293571,12.913614,15.453452,14.280357,11.396988,14.017531,9.250833,...,15.023735,10.538333,7.262262,8.210714,8.887738,9.588675,11.746548,14.238929,7.276071,11.025119
std,3.651251,4.206694,5.159234,5.758398,5.550996,4.293609,4.533987,4.891763,4.275753,3.532203,...,5.548657,4.935983,3.601251,5.832874,3.939606,5.001208,5.132911,4.347334,3.489678,5.611448